import 'package:dart_rethrowing_exceptions/dart_rethrowing_exceptions.dart';
import 'package:test/test.dart';

void main() {
  test('calculate', () {
    expect(calculate(), 42);
  });
}
